/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectos.reto5.views;

import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import proyectos.reto5.controlador.ControladorRequerimientos;
import proyectos.reto5.modelo.vo.Requerimiento_1;
import proyectos.reto5.modelo.vo.Requerimiento_2;
import proyectos.reto5.modelo.vo.Requerimiento_3;

/**
 *
 * @author sergi
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Consulta3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        BotonConsultar1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSiPagados = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        Eliminar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BotonConsultar2 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Eliminar2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        BotonConsultar3 = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla3 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        BotonEliminar3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyectos Vivienda");

        jLabel1.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 24)); // NOI18N
        jLabel1.setText("Proyectos Vivienda");

        BotonConsultar1.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 24)); // NOI18N
        BotonConsultar1.setText("Consultar");
        BotonConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultar1ActionPerformed(evt);
            }
        });

        TablaSiPagados.setBorder(new javax.swing.border.MatteBorder(null));
        TablaSiPagados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TablaSiPagados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                
            }
        ));
        jScrollPane1.setViewportView(TablaSiPagados);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Conoce el id de las compras que si estén pagadas");

        Eliminar1.setText("Limpiar");
        Eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(BotonConsultar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Eliminar1)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonConsultar1)
                    .addComponent(Eliminar1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Consulta3.addTab("Consulta1", jPanel1);

        BotonConsultar2.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 24)); // NOI18N
        BotonConsultar2.setText("Consultar");
        BotonConsultar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultar2ActionPerformed(evt);
            }
        });

        Tabla2.setBorder(new javax.swing.border.MatteBorder(null));
        Tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                
            }
        ));
        jScrollPane2.setViewportView(Tabla2);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Conoce el id de todas las compras cuyo precio por unidad de su material de ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("construcción sea inferior a 1100");

        Eliminar2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Eliminar2.setText("Limpiar");
        Eliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(BotonConsultar2)
                        .addGap(139, 139, 139)
                        .addComponent(Eliminar2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonConsultar2)
                    .addComponent(Eliminar2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Consulta3.addTab("Consulta2", jPanel2);

        BotonConsultar3.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 24)); // NOI18N
        BotonConsultar3.setText("Consultar");
        BotonConsultar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultar3ActionPerformed(evt);
            }
        });

        Tabla3.setBorder(new javax.swing.border.MatteBorder(null));
        Tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                
            }
        ));
        jScrollPane3.setViewportView(Tabla3);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Obten el id de la compra y el año de las compras pagadas parcialmente y en el mes '02'");

        BotonEliminar3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonEliminar3.setText("Limpiar");
        BotonEliminar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonConsultar3)
                .addGap(127, 127, 127)
                .addComponent(BotonEliminar3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonConsultar3)
                    .addComponent(BotonEliminar3))
                .addGap(36, 36, 36))
        );

        Consulta3.addTab("Consulta3", jPanel3);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Realize aquí sus consultas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(252, 252, 252))
                    .addComponent(Consulta3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(Consulta3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static final ControladorRequerimientos controlador = new ControladorRequerimientos();

    private void BotonConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultar1ActionPerformed
        String[] columnNombre={"ID_Compra","Pagado","Proveedor"};
        try {
            ArrayList <Requerimiento_1> lista = controlador.consultarRequerimiento1();
            Object[][] datos = new Object[lista.size()][3];

            for (int i = 0 ; i < lista.size();i++) {
                datos[i][0] = lista.get(i).getID_Compra();
                datos[i][1] = lista.get(i).getPagado();
                datos[i][2] = lista.get(i).getProveedor();
            }
            
            DefaultTableModel model = new DefaultTableModel(datos,columnNombre);
            TablaSiPagados.setModel(model);
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }//GEN-LAST:event_BotonConsultar1ActionPerformed

    private void BotonConsultar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultar2ActionPerformed
        String[] columnNombre={"ID_Compra","ID_Material_Construccion","Material_Construccion","Precio_Unidad"};
        try {
            ArrayList <Requerimiento_2> lista = controlador.consultarRequerimiento2();
            Object[][] datos = new Object[lista.size()][4];

            for (int i = 0 ; i < lista.size();i++) {
                datos[i][0] = lista.get(i).getID_Compra();
                datos[i][1] = lista.get(i).getID_MaterialConstruccion();
                datos[i][2] = lista.get(i).getNombre_Material();
                datos[i][3] = lista.get(i).getPrecio_Unidad();
            }
            
            DefaultTableModel model = new DefaultTableModel(datos,columnNombre);
            Tabla2.setModel(model);
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
    

    private void BotonConsultar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultar3ActionPerformed
        String[] columnNombre={"ID_Compra","Pagado","Fecha"};
        try {
            ArrayList <Requerimiento_3> lista = controlador.consultarRequerimiento3();
            Object[][] datos = new Object[lista.size()][3];

            for (int i = 0 ; i < lista.size();i++) {
                datos[i][0] = lista.get(i).getID_Compra();
                datos[i][1] = lista.get(i).getPagado();
                datos[i][2] = lista.get(i).getFecha();
            }
            
            DefaultTableModel model = new DefaultTableModel(datos,columnNombre);
            Tabla3.setModel(model);
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    private void Eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar1ActionPerformed
        int confirmar=JOptionPane.showConfirmDialog(null,"¡¿Esta seguro de que desea limpiar?!");
        if(confirmar==JOptionPane.OK_OPTION){
            TablaSiPagados.setModel(new DefaultTableModel());
        }else{
            JOptionPane.showMessageDialog(null,"Operacion cancelada");
        }
    }

    private void Eliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar2ActionPerformed
        int confirmar=JOptionPane.showConfirmDialog(null,"¡¿Esta seguro de que desea limpiar?!");
        if(confirmar==JOptionPane.OK_OPTION){
            Tabla2.setModel(new DefaultTableModel());
        }else{
            JOptionPane.showMessageDialog(null,"Operacion cancelada");
        }
    }

    private void BotonEliminar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminar3ActionPerformed
        int confirmar=JOptionPane.showConfirmDialog(null,"¡¿Esta seguro de que desea limpiar?!");
        if(confirmar==JOptionPane.OK_OPTION){    
            Tabla3.setModel(new DefaultTableModel());
        }else{
            JOptionPane.showMessageDialog(null,"Operacion cancelada");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonConsultar1;
    private javax.swing.JToggleButton BotonConsultar2;
    private javax.swing.JToggleButton BotonConsultar3;
    private javax.swing.JButton BotonEliminar3;
    private javax.swing.JTabbedPane Consulta3;
    private javax.swing.JButton Eliminar1;
    private javax.swing.JButton Eliminar2;
    private javax.swing.JTable Tabla2;
    private javax.swing.JTable Tabla3;
    private javax.swing.JTable TablaSiPagados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
